name    'atlasit-bacula'
version '0.1.0'
source 'https://github.com/desalvo/puppet-bacula'
author 'desalvo'
license 'Apache License, Version 2.0'
summary 'Puppet module for bacula'
description 'Puppet module for bacula configuration'
project_page 'https://github.com/desalvo/puppet-bacula'
