name    'desalvo-bacula'
version '0.2.1'
source 'https://github.com/desalvo/puppet-bacula'
author 'desalvo'
license 'Apache License, Version 2.0'
summary 'Puppet module for bacula'
description 'Puppet module for bacula configuration'
project_page 'https://github.com/desalvo/puppet-bacula'
dependency 'puppetlabs/mysql', '>= 0.9.0'
dependency 'puppetlabs/apache', '>= 0.10.0'
