#!/bin/sh
#
# shell script to grant privileges to the bacula database
#
bindir=/usr/bin
db_name="$1"
db_user="$2"
db_password="$3"
if [ "$db_password" != "" ]; then
   pass="identified by '$db_password'"
fi
shift 3

if $bindir/mysql $* -u root -f <<END-OF-DATA
use mysql
grant all privileges on ${db_name}.* to ${db_user}@localhost ${pass};
grant all privileges on ${db_name}.* to ${db_user}@"%" ${pass};
select * from user;
flush privileges;
END-OF-DATA
then
   echo "Privileges for user ${db_user} granted on database ${db_name}."
   exit 0
else
   echo "Error creating privileges."
   exit 1
fi
